name: Tests

on:
  push:
    branches:
      - master
      - beta
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: yarn install and test
        run: |
          yarn install
          yarn test
        env:
          CI: true
